arch = [
	"feh",
	"mpv",
	"mupdf",
	"unzip",
	"spotify",
	"waydroid",
	"inkscape",
	"mcreator",
	"smassh-bin",
	"kdeconnect",
	"obs-studio",
	"qutebrowser",
	"orca-slicer-bin",
	"libreoffice-fresh",
	"programmer-calculator",
	"zen-browser-compat-bin",
]
