arch = [
	"ly",
	"vim",
	"gtk2",
	"grub",
	"nano",
	"paru",
	"bluez",
	"fbset",
	"neovim",
	"ntfs-3g",
	"chezmoi",
	"fprintd",
	"amd-ucode", 
	"metapac-bin",
	"bluez-utils",
	"brightnessctl",

	"base", 
	"base-devel",

	"linux-lts",
	"linux-firmware",
	"linux-lts-headers",

	"pipewire",
	"wireplumber", 
	"pipewire-pulse",
]
