arch = [
	"fbset",
	"gtk2",
	"amd-ucode", 
	"base", 
	"base-devel",
	"bluez",
	"bluez-utils",
	"brightnessctl",
	"fprintd",
	"grub",
	"linux-firmware",
	"linux-lts",
	"linux-lts-headers",
	"ly",
	"metapac-bin",
	"nano",
	"ntfs-3g",
	"paru",
	"pipewire",
	"pipewire-pulse",
	"vim",
	"neovim",
	"wireplumber", "chezmoi",
]
