arch = [
	"mako",
	"niri",
	"wayclip",
	"hypridle",
	"hyprlock",
	"libnotify",
	"hyprpaper",
	"lasso-launcher",
	"python-pywal16",
	"python-pywalfox",
	"ttf-cascadia-code-nerd",
	"bibata-cursor-theme-bin",
]

