arch = [
	"mako",
	"wayclip",
	"niri-git",
	"hypridle",
	"hyprlock",
	"libnotify",
	"hyprpaper",
	"lasso-launcher",
	"python-pywal16",
	"python-pywalfox",
	"xwayland-satellite",
	"ttf-cascadia-code-nerd",
	"bibata-cursor-theme-bin",
]

