arch = [
	"python-pywal16",
	"python-pywalfox",
	"bibata-cursor-theme-bin",
	"hypridle",
	"hyprlock",
	"lasso-launcher",
	"mako",
	"niri",
	"ttf-cascadia-code-nerd",
	"xdg-desktop-portal-hyprland",
	"wayclip",
	"libnotify"
]

